[project]
name = "testing-goat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.8",
    "pytest>=8.4.2",
    "pytest-playwright>=0.7.1",
    "ruff>=0.14.3",
]
